export const createCommunitySubtitles = [
  '...for your favorite subject.',
  '...for your favourite tea.',
  '...why not Zoidberg.',
  '...because you love freedom.',
  '...because you hate freedom.',
  '...for a fringe candidate.',
  '...for your favorite hobby.',
  '...for your favorite TV show.',
  '...for your WoW guild.',
  '...for your favorite game.',
  '...for your school.',
  '...for your project.',
  '...for great justice.',
  '...for your office.',
  '...for your community.',
  '...for your classroom.',
  '...for your hobby.',
  '...for your town.',
  '...for your movement.',
  '...do it for the children.',
];
