export const createCommunitySubtitles = [
  '...unstoppable by design.',
  '...servers are overrated.',
  '...cryptographic playground.',
  '...where you own the keys.',
  '...no middleman here.',
  '...join the decentralution.',
  '...because privacy matters.',
  '...freedom served fresh daily.',
  '...your community, your rules.',
  '...no gods, no global admins.',
  '...centralization is boring.',
  '...torrents, but for thoughts.',
  '...can’t stop the signal.',
  '...fully yours, forever.',
  '...powered by caffeine.',
  '...speech wants to be free.',
  '...crypto-certified community.',
  '...take ownership literally.',
  '...your ideas, decentralized.',
  '...for digital sovereignty.',
];
